"use client"
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { FormattedMessage } from 'react-intl'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  const {locale} = useRouter()
  const langName = locale === 'en' ? 'English' : 'العربية'
  console.log({locale})
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          <FormattedMessage id='title' />
        </h1>
        <h5>
          <FormattedMessage id='language' values={{name: langName}} />
        </h5>
        
        <Link href='/' locale={locale}>
          Go Home
        </Link>
      </main>
    </>
  )
}
